### ISSUE TITLE
Bad Syntax from script run

### ISSUE THREAD

**Issue by tupphelper** [fsmMLK/inkscapeCartesianAxes2D#1]
I had a dialog window present this return:
Traceback (most recent call last):
  File "cartesianAxes2D.py", line 25, in <module>
    import inkscapeMadeEasy_Base as inkBase
  File "C:\Users\dipol\AppData\Roaming\inkscape\extensions\inkscapeMadeEasy_Base.py", line 461
    accepted_strings = {inkex.addNS('path', 'svg'), inkex.addNS('text', 'svg'), 'g', 'path'}
                                                  ^
SyntaxError: invalid syntax

Any ideas? Did I get the wrong version of inkscapeMadeEasy_Base? And is this python syntax rules?

**Comment by fsmMLK** [comment]
This should be a valid sintax to define a set (https://docs.python.org/3/tutorial/datastructures.html, section 5.4). Which version of python are you using?

I will check my code in Windows too see if I can reproduce the problem.

**Comment by su-v** [comment]
Windows packages (32bit, 64bit) for current stable Inkscape (0.91) use **Python 2.6.5**. Based on the Python docs, the syntax with curly braces is new in **Python 2.7**:

> As of Python 2.7, non-empty sets (not frozensets) can be created by placing a comma-separated list of elements within braces, for example: {'jack', 'sjoerd'}, in addition to the set constructor.

https://docs.python.org/2/library/stdtypes.html#set-types-set-frozenset

Note that Windows packages for the next major Inkscape release (0.92) will include [**Python 2.7.11**](https://bugs.launchpad.net/inkscape/+bug/1575790).

**Comment by fsmMLK** [comment]
Ok, we might have found the culprit. I'm using python 2.7 in linux. I will fix it ASAP. =)

**Comment by fsmMLK** [comment]
I uploaded a new version of inkscapeMadeEasy. Please check whether it works for you now.

**Comment by tupphelper** [comment]
This appears to have resolved the bad syntax error thank you.
