### ISSUE TITLE
Missing textext dependecies?

### ISSUE THREAD

**Issue by tupphelper** [fsmMLK/inkscapeCartesianAxes2D#2]
i got this return after attempting to run the default settings for the CartesianAxes2D extension window: 

C:\Users\dipol\AppData\Roaming\inkscape\extensions\textextLib\textext.py:62: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import os, sys, tempfile, traceback, glob, re, md5, copy
Traceback (most recent call last):
  File "cartesianAxes2D.py", line 26, in <module>
    import inkscapeMadeEasy_Draw as inkDraw
  File "C:\Users\dipol\AppData\Roaming\inkscape\extensions\inkscapeMadeEasy_Draw.py", line 30, in <module>
    import textextLib.textext as textext
  File "C:\Users\dipol\AppData\Roaming\inkscape\extensions\textextLib\textext.py", line 321, in <module>
    raise RuntimeError("Neither pygtk nor Tkinter is available!")
RuntimeError: Neither pygtk nor Tkinter is available!

I'm not entirely up on python syntax having not coded in it in particular but it appears that  there are two "try"  blocks for importing the pygtk and Tkinter modules. Do I need to go download these files and put them in the textext directory?

**Comment by su-v** [comment]
Ideally (for cross-platform support of the basic features), the entire usage of LaTeX (and thus also textext) could be implemented as optional feature: precompiled Inkscape packages for non-Linux platforms (i.e. Windows, OS X)
- do not support LaTeX out-of-the-box
- do not include `pygtk`  
  (Inkscape's bundled extensions rely on the built-in Auto-GUI feature based on INX files)
- might not have `Tkinter` available

`pygtk` and `Tkinter` are binary python modules with external dependencies - users of precompiled Inkscape packages cannot easily add such modules themselves.

**Comment by fsmMLK** [comment]
Those issues come from textext extension. I have a partially working implementation of inkscapeMadeEasy where you can choose whether you want to use latex or not.

I am working on it now.

**Comment by tupphelper** [comment]
Well you keep working on that. For my purposes if I install python on windows ten and install pygtk will this resolve my dependencies issues? Will I have to get all of this under the extensions directory? 

Do either of you have any experience trying to get pygtk to install? I got phython to install but the pygtk installers swear that I don't have python 2.7 anywhere.

**Comment by fsmMLK** [comment]
I just uploaded a new version of inkscapeMadeEasy where LaTeX support is optional. Please check documentation (https://fsmmlk.github.io/inkscapeMadeEasy/#installation-and-requirements) on how to disable LaTeX support. By disabling it, you will not need pygtk and Tkinter. I will update the documentations informing this new feature.

Please check whether it works now for you.

ps: BTW, installing Python and its modules in Windows can be a pain.

**Comment by tupphelper** [comment]
Alright, thank you, I'll get back to you perhaps tonight about trying out the new feature.

**Comment by tupphelper** [comment]
So I downloaded the new version and uncommented so that the variable is False. I can now use this extension to create the Axes plot. 

You may want to move the origin of the x-axis label to underneath the x-axis if the x-min = 0, because it looks a bit strange when I do a single quadrant graph and the x-axis label is stuck out to the right (and could end up being almost as long as the visible x-axis).

**Comment by fsmMLK** [comment]
This is something I have been thinking about. For short axis labels, positioning near the end is aesthetically OK (and necessary if the axis crosses the middle of the Cartesian area). For long labels, centering it along the axis (above/below) seems better. The question is: Is it worth adding one extra config param. to choose or would it be better/easier to do move it manually after you have your plot? I am inclined to the later but I am open to suggestions.
