### ISSUE TITLE
Edit an existing coordinate system

### ISSUE THREAD

**Issue by bshOriginal** [fsmMLK/inkscapeCartesianAxes2D#7]
It would be very useful if an existing coordinate system allows (a posteriori) editing (Axis lables, Axis color, Grid color, etc.).

![Screenshot_20210408_162142](https://user-images.githubusercontent.com/4884200/114043345-7facc200-9886-11eb-9b9f-91729ddf86a4.png)

I haven't found any options in inkscape to edit the coordinate system created by the cartesianAxes2D plugin.

**Comment by fsmMLK** [comment]
Even if I save all the parameters as one custom attribute of the node (xml file) There is no way to send that information to the GUI when you run the extension. Therefore, the previous parameters cannot be presented to the user for modifications.
